<?php
// $Id: mbda_social_network.module,v 1.0 2010/06/22 00:00:00 vyelamanchili Exp $

/**
 * @file
 * Module for customizing the Quick links
 */

/**
 * Implemenetation of hook_init();
 */

function mbda_social_network_init() {
	drupal_add_css(drupal_get_path('module', 'mbda_social_network') .'/css/mbda_social_network_style.css');
}

/**
 * Displays help and information about this module 
 * 
 * @param path the path where the help will be displayed
 * @param arg array that holds the current path as would be returned from arg() function
 * 
 * @return help text for the path
 *
 * Implementation of hook_help()
 */ 
 function mbda_social_network_help($path, $arg) {
	$output = '';
  switch($path) {
	  case 'admin/help#mbda_social_network':
			$output = '<p>' . t("This module is used to display the status updates from various social networking sites like twitter and facebook.") . '</p>';
			break;
	 }
	return $output;
}
   
/**
 * Valid permissions for this module
 * 
 * @return array An array of valid permissions for the mbda_social_network
 *
 * Implementation of hook_perm()
 */ 
function mbda_social_network_perm() {
	return array("edit settings", );
}
 
/**
 * Implemenetation of hook_menu();
 */
function mbda_social_network_menu() {
	$items = array();
	$items['admin/settings/mbdasocialsettings'] = array(
		'title' => t('MBDA Social Network settings'),
		'description' => t('Module to manage social network updates.'),
  	'page callback' => 'drupal_get_form',
  	'page arguments' => array('mbda_social_network_admin_form'),
  	'access arguments' => array('edit settings'),
  	'type' => MENU_NORMAL_ITEM,
  );

	return $items;	
}

/**
 * This function is the admin form for displlaying options to edit settings for the social updates
 */
function mbda_social_network_admin_form() {
	$form['mbda_social_network_twitter_username'] = array(
																				'#type' => 'textfield',
																				'#title' => t('Twitter Username'),
																				'#default_value' => variable_get('mbda_social_network_twitter_username', 'USMBDA'),
																			);
 	$form['mbda_social_network_updates_count'] = array(
																				'#type' => 'textfield',
																				'#title' => t('Number of items'),
																				'#default_value' => variable_get('mbda_social_network_updates_count', 6),
																			);
																			
  return system_settings_form($form);
}

/**
 * Implementation of hook_block()
 *
 */
function mbda_social_network_block($op = 'list', $delta = 0, $edit = array()) {
  switch($op) {
	
		case 'list': 	
			$blocks[0]['info'] = t('MBDA Social Network Updates');
			return $blocks;

  	case 'configure':	
			$form['mbda_social_network_twitter_username'] = array(
																				'#type' => 'textfield',
																				'#title' => t('Twitter Username'),
																				'#default_value' => variable_get('mbda_social_network_twitter_username', 'USMBDA'),
																			);
    	$form['mbda_social_network_updates_count'] = array(
				'#type' => 'textfield',
				'#title' => t('Number of items'),
				'#default_value' => variable_get('mbda_social_network_updates_count', 6),
			);
	    return $form;

	case 'save': 
    variable_set('mbda_social_network_twitter_username', $edit['mbda_social_network_twitter_username']);
    variable_set('mbda_social_network_updates_count', $edit['mbda_social_network_updates_count']);
  
  case 'view': 
    $block['subject'] = t('MBDA Social Network');
		$block['content'] = mbda_social_network_get_statuses();
		
    return $block;
 	}
}

/**
 * This function retrieves the list of statuses to display
 */
function mbda_social_network_get_statuses() {
  $username = variable_get('mbda_social_network_twitter_username', 'USMBDA');
  $count = variable_get('mbda_social_network_updates_count', 6);
  
	$exec_query = db_query("SELECT statustext, tweetid, link, creation_date 
													FROM {mbda_social_network_twitter_statuses} 
													ORDER BY creation_date desc LIMIT 0,%d", $count);
	
	$text ='<div id="mbda_social_network_updates_block"><ul>';
	while($listitem = db_fetch_array($exec_query)) {
		$text .= '<li class="twitter_block_li">"'
							.$listitem['statustext'].' '
							.'"<br>posted on '.(date("m-d-Y",($listitem['creation_date']))).' '
							.'by <a href="/goto?destination='.$listitem['link'].'">'.$username.'</a><br /><br/></li>';
	}
	$text .= '</ul></div>';
	
	return $text;
}

/**
 * This function retrieves the status from the xml and stores in the database
 *
 * Implementation of hook_cron()
 */
function mbda_social_network_cron(){
	$userid = variable_get('mbda_social_network_twitter_username', 'USMBDA');

	$url = "http://twitter.com/statuses/user_timeline/$userid.xml?count=10";
	
	$xml = simplexml_load_file($url) or drupal_set_message("Could not connect to twitter", 'error');
	
	foreach($xml->status as $status) {
		$itemToInsert['tweetid'] = $status->id;
		$itemToInsert['statustext'] = $status->text;
		$itemToInsert['creation_date'] = strtotime($status->created_at);
		$itemToInsert['link'] = 'http://twitter.com/'.$status->user->screen_name.'/statuses/'.$status->id;

		$insertCheckFlag = FALSE;
		
		while(db_fetch_array(db_query("SELECT tweetid FROM {mbda_social_network_twitter_statuses} WHERE tweetid = '%s'", array($status->id)))) {
			drupal_write_record('mbda_social_network_twitter_statuses', $itemToInsert, 'tweetid');
			$insertCheckFlag = TRUE;
		}
		
		if(!$insertCheckFlag) {
			drupal_write_record('mbda_social_network_twitter_statuses', $itemToInsert);
		}
  }
}